USE master
GO
IF (DB_ID('Scratch') IS NULL)
BEGIN
    CREATE DATABASE Scratch;
END
GO
USE Scratch
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF (OBJECT_ID('dbo.NorthCarolinaPopulation') IS NULL)
BEGIN
    CREATE TABLE [dbo].[NorthCarolinaPopulation]
    (
        [City] [nvarchar](50) NOT NULL,
        [Counties] [nvarchar](50) NOT NULL,
        [Population] [int] NOT NULL
    ) ON [PRIMARY]
END
GO
USE [Scratch]
IF NOT EXISTS
(
	SELECT 1
	FROM dbo.NorthCarolinaPopulation
)
BEGIN
	INSERT [dbo].[NorthCarolinaPopulation] ([City], [Counties], [Population])
	VALUES
		(N'Fontana Dam', N'GRAHAM', 20),
		(N'Grandfather Village', N'AVERY', 25),
		(N'Lake Santeetlah', N'GRAHAM', 43),
		(N'Leggett', N'EDGECOMBE', 59),
		(N'Bear Grass', N'MARTIN', 73),
		(N'Speed', N'EDGECOMBE', 81),
		(N'Hassell', N'MARTIN', 84),
		(N'Centerville', N'FRANKLIN', 88),
		(N'Como', N'HERTFORD', 91),
		(N'Orrum', N'ROBESON', 92),
		(N'Lumber Bridge', N'ROBESON', 93),
		(N'Raynham', N'ROBESON', 95),
		(N'Falkland', N'PITT', 97),
		(N'Harrellsville', N'HERTFORD', 105),
		(N'Chimney Rock Village', N'RUTHERFORD', 111),
		(N'McDonald', N'ROBESON', 111),
		(N'Seven Springs', N'WAYNE', 114),
		(N'Proctorville', N'ROBESON', 115),
		(N'Macon', N'WARREN', 117),
		(N'McFarlan', N'ANSON', 117),
		(N'Love Valley', N'IREDELL', 120),
		(N'Indian Beach', N'CARTERET', 121),
		(N'Lasker', N'NORTHAMPTON', 121),
		(N'Tar Heel', N'BLADEN', 122),
		(N'Linden', N'CUMBERLAND', 127),
		(N'Middleburg', N'VANCE', 134),
		(N'Godwin', N'CUMBERLAND', 138),
		(N'Norman', N'RICHMOND', 138),
		(N'Boardman', N'COLUMBUS', 153),
		(N'Bolivia', N'BRUNSWICK', 154),
		(N'Lansing', N'ASHE', 155),
		(N'Everetts', N'MARTIN', 159),
		(N'Bald Head Island', N'BRUNSWICK', 171),
		(N'Milton', N'CASWELL', 172),
		(N'Pantego', N'BEAUFORT', 176),
		(N'Marietta', N'ROBESON', 176),
		(N'Danbury', N'STOKES', 184),
		(N'Eureka', N'WAYNE', 193),
		(N'Colerain', N'BERTIE', 195),
		(N'Cerro Gordo', N'COLUMBUS', 197),
		(N'Sugar Mountain', N'AVERY', 197),
		(N'Autryville', N'SAMPSON', 199),
		(N'Crossnore', N'AVERY', 201),
		(N'Harrells', N'SAMPSON/DUPLIN', 204),
		(N'Seven Devils', N'WATAUGA/AVERY', 208),
		(N'Watha', N'PENDER', 214),
		(N'Mesic', N'PAMLICO', 215),
		(N'Walstonburg', N'GREENE', 216),
		(N'Momeyer', N'NASH', 216),
		(N'Roxobel', N'BERTIE', 225),
		(N'Seagrove', N'RANDOLPH', 227),
		(N'Dillsboro', N'JACKSON', 228),
		(N'Halifax', N'HALIFAX', 231),
		(N'Askewville', N'BERTIE', 235),
		(N'Kelford', N'BERTIE', 237),
		(N'Bath', N'BEAUFORT', 242),
		(N'Vandemere', N'PAMLICO', 250),
		(N'Castalia', N'NASH', 255),
		(N'Powellsville', N'BERTIE', 261),
		(N'Earl', N'CLEVELAND', 266),
		(N'Creswell', N'WASHINGTON', 267),
		(N'Severn', N'NORTHAMPTON', 270),
		(N'Parmele', N'MARTIN', 273),
		(N'Stonewall', N'PAMLICO', 279),
		(N'Conetoe', N'EDGECOMBE', 280),
		(N'Goldston', N'CHATHAM', 280),
		(N'Sandy Creek', N'BRUNSWICK', 281),
		(N'Cedar Rock', N'CALDWELL', 292),
		(N'East Laurinburg', N'SCOTLAND', 294),
		(N'Casar', N'CLEVELAND', 296),
		(N'Sims', N'WILSON', 305),
		(N'Oak City', N'MARTIN', 306),
		(N'Turkey', N'SAMPSON', 307),
		(N'Falcon', N'CUMBERLAND/SAMPSON', 313),
		(N'Gatesville', N'GATES', 313),
		(N'Cameron', N'MOORE', 314),
		(N'Mooresboro', N'CLEVELAND', 316),
		(N'Trenton', N'JONES', 317),
		(N'Waco', N'CLEVELAND', 321),
		(N'Bethania', N'FORSYTH', 325),
		(N'Beech Mountain', N'WATAUGA/AVERY', 327),
		(N'Atkinson', N'PENDER', 329),
		(N'Hobgood', N'HALIFAX', 333),
		(N'Pollocksville', N'JONES', 336),
		(N'Hayesville', N'CLAY', 338),
		(N'Bunn', N'FRANKLIN', 345),
		(N'Dublin', N'BLADEN', 351),
		(N'Webster', N'JACKSON', 369),
		(N'Forest Hills', N'JACKSON', 369),
		(N'Brookford', N'CATAWBA', 374),
		(N'Teachey', N'DUPLIN', 385),
		(N'Bostic', N'RUTHERFORD', 387),
		(N'Dover', N'CRAVEN', 387),
		(N'Rennert', N'ROBESON', 389),
		(N'Cove City', N'CRAVEN', 390),
		(N'Duck', N'DARE', 392),
		(N'Hamilton', N'MARTIN', 398),
		(N'Topsail Beach', N'PENDER', 401),
		(N'Hookerton', N'GREENE', 403),
		(N'Staley', N'RANDOLPH', 403),
		(N'Cofield', N'HERTFORD', 407),
		(N'Saratoga', N'WILSON', 409),
		(N'Ronda', N'WILKES', 414),
		(N'Simpson', N'PITT', 414),
		(N'Peachland', N'ANSON', 417),
		(N'St. Helena', N'PENDER', 420),
		(N'Stovall', N'GRANVILLE', 421),
		(N'Fountain', N'PITT', 429),
		(N'Parkton', N'ROBESON', 436),
		(N'Salemburg', N'SAMPSON', 436),
		(N'Caswell Beach', N'BRUNSWICK', 442),
		(N'Washington Park', N'BEAUFORT', 444),
		(N'Ruth', N'RUTHERFORD', 448),
		(N'Grimesland', N'PITT', 449),
		(N'Elk Park', N'AVERY', 450),
		(N'MacClesfield', N'EDGECOMBE', 455),
		(N'Sandyfield', N'COLUMBUS', 455),
		(N'Micro', N'JOHNSTON', 456),
		(N'Lattimore', N'CLEVELAND', 459),
		(N'Bridgeton', N'CRAVEN', 460),
		(N'Bakersville', N'MITCHELL', 469),
		(N'Minnesott Beach', N'PAMLICO', 470),
		(N'East Arcadia', N'BLADEN', 478),
		(N'Jamesville', N'MARTIN', 479),
		(N'Morven', N'ANSON', 484),
		(N'Jackson', N'NORTHAMPTON', 487),
		(N'Aurora', N'BEAUFORT', 506),
		(N'Kittrell', N'VANCE', 517),
		(N'Gibson', N'SCOTLAND', 522),
		(N'Lilesville', N'ANSON', 529),
		(N'Lewiston Woodville', N'BERTIE', 530),
		(N'Pink Hill', N'LENOIR', 531),
		(N'Stem', N'GRANVILLE', 539),
		(N'Harmony', N'IREDELL', 540),
		(N'Polkville', N'CLEVELAND', 544),
		(N'Bailey', N'NASH', 545),
		(N'Wade', N'CUMBERLAND', 553),
		(N'Calypso', N'DUPLIN', 556),
		(N'Newton Grove', N'SAMPSON', 561),
		(N'Arapahoe', N'PAMLICO', 567),
		(N'Ossipee', N'ALAMANCE', 569),
		(N'Hoffman', N'RICHMOND', 570),
		(N'Hot Springs', N'MADISON', 573),
		(N'Roper', N'WASHINGTON', 586),
		(N'East Bend', N'YADKIN', 595),
		(N'Varnamtown', N'BRUNSWICK', 596),
		(N'Rosman', N'TRANSYLVANIA', 599),
		(N'Robbinsville', N'GRAHAM', 603),
		(N'Catawba', N'CATAWBA', 604),
		(N'Lawndale', N'CLEVELAND', 604),
		(N'Seaboard', N'NORTHAMPTON', 604),
		(N'Whitsett', N'GUILFORD', 604),
		(N'Winfall', N'PERQUIMANS', 607),
		(N'Fallston', N'CLEVELAND', 609),
		(N'Ansonville', N'ANSON', 610),
		(N'New London', N'STANLY', 616),
		(N'Patterson Springs', N'CLEVELAND', 621),
		(N'Holden Beach', N'BRUNSWICK', 622),
		(N'Ocean Isle Beach', N'BRUNSWICK', 622),
		(N'Richfield', N'STANLY', 631),
		(N'Garland', N'SAMPSON', 639),
		(N'Sedalia', N'GUILFORD', 644),
		(N'Littleton', N'HALIFAX', 651),
		(N'Greenevers', N'DUPLIN', 654),
		(N'McAdenville', N'GASTON', 670),
		(N'Pikeville', N'WAYNE', 672),
		(N'Misenheimer', N'STANLY', 672),
		(N'Kingstown', N'CLEVELAND', 676),
		(N'Peletier', N'CARTERET', 676),
		(N'Bolton', N'COLUMBUS', 690),
		(N'Grantsboro', N'PAMLICO', 692),
		(N'High Shoals', N'GASTON/LINCOLN', 699),
		(N'Grover', N'CLEVELAND', 712),
		(N'Newland', N'AVERY', 712),
		(N'Whitakers', N'EDGECOMBE/NASH', 714),
		(N'Bogue', N'CARTERET', 725),
		(N'Saluda', N'POLK/HENDERSON', 731),
		(N'Winton', N'HERTFORD', 734),
		(N'Taylortown', N'MOORE', 744),
		(N'Red Cross', N'STANLY', 754),
		(N'Vass', N'MOORE', 755),
		(N'Woodland', N'NORTHAMPTON', 767),
		(N'Black Creek', N'WILSON', 768),
		(N'North Topsail Beach', N'ONSLOW', 768),
		(N'Stantonsburg', N'WILSON', 781),
		(N'Alliance', N'PAMLICO', 786),
		(N'Montreat', N'BUNCOMBE', 791),
		(N'Middlesex', N'NASH', 800),
		(N'Northwest', N'BRUNWICK/BRUNSWICK', 807),
		(N'Chocowinity', N'BEAUFORT', 821),
		(N'Kenansville', N'DUPLIN', 821),
		(N'Faith', N'ROWAN', 823),
		(N'Wagram', N'SCOTLAND', 830),
		(N'Columbia', N'TYRRELL', 835),
		(N'Conway', N'NORTHAMPTON', 835),
		(N'Dobbins Heights', N'RICHMOND', 838),
		(N'Candor', N'MONTGOMERY', 840),
		(N'Walnut Creek', N'WAYNE', 846),
		(N'Warrenton', N'WARREN', 847),
		(N'Aulander', N'BERTIE', 850),
		(N'White Lake', N'BLADEN', 853),
		(N'Clarkton', N'BLADEN', 856),
		(N'Star', N'MONTGOMERY', 856),
		(N'Ellenboro', N'RUTHERFORD', 879),
		(N'Cleveland', N'ROWAN', 882),
		(N'Marshall', N'MADISON', 894),
		(N'Old Fort', N'MCDOWELL', 902),
		(N'Oriental', N'PAMLICO', 906),
		(N'Highlands', N'MACON/JACKSON', 928),
		(N'Fair Bluff', N'COLUMBUS', 942),
		(N'Rich Square', N'NORTHAMPTON', 943),
		(N'Belwood', N'CLEVELAND', 944),
		(N'Magnolia', N'DUPLIN', 964),
		(N'Cooleemee', N'DAVIE', 965),
		(N'Columbus', N'POLK', 979),
		(N'Dortches', N'NASH', 983),
		(N'Faison', N'DUPLIN/SAMPSON', 992),
		(N'Vanceboro', N'CRAVEN', 993),
		(N'Foxfire Village', N'MOORE', 1016),
		(N'Rowland', N'ROBESON', 1017),
		(N'Garysburg', N'NORTHAMPTON', 1023),
		(N'Ellerbe', N'RICHMOND', 1029),
		(N'Alamance', N'ALAMANCE', 1047),
		(N'Stoneville', N'ROCKINGHAM', 1053),
		(N'Maysville', N'JONES', 1060),
		(N'Stedman', N'CUMBERLAND', 1071),
		(N'Rhodhiss', N'BURKE/CALDWELL', 1081),
		(N'Norlina', N'WARREN', 1101),
		(N'Brunswick', N'COLUMBUS', 1122),
		(N'Mount Gilead', N'MONTGOMERY', 1122),
		(N'Gaston', N'NORTHAMPTON', 1130),
		(N'Robbins', N'MOORE', 1137),
		(N'Lucama', N'WILSON', 1143),
		(N'Banner Elk', N'AVERY', 1161),
		(N'Franklinville', N'RANDOLPH', 1192),
		(N'Roseboro', N'SAMPSON', 1192),
		(N'Lake Lure', N'RUTHERFORD', 1210),
		(N'Boonville', N'YADKIN', 1216),
		(N'Princeton', N'JOHNSTON', 1223),
		(N'Clyde', N'HAYWOOD', 1232),
		(N'Fremont', N'WAYNE', 1241),
		(N'Bayboro', N'PAMLICO', 1245),
		(N'Swepsonville', N'ALAMANCE', 1260),
		(N'Broadway', N'LEE/HARNETT', 1272),
		(N'Blowing Rock', N'WATAUGA/CALDWELL', 1287),
		(N'Maggie Valley', N'HAYWOOD', 1289),
		(N'Youngsville', N'FRANKLIN', 1300),
		(N'Pinetops', N'EDGECOMBE', 1314),
		(N'Spring Hope', N'NASH', 1320),
		(N'Beulaville', N'DUPLIN', 1326),
		(N'Elm City', N'WILSON', 1326),
		(N'West Jefferson', N'ASHE', 1334),
		(N'Kenly', N'JOHNSTON/WILSON', 1359),
		(N'Pine Knoll Shores', N'CARTERET', 1367),
		(N'Rutherford College', N'BURKE', 1368),
		(N'Walnut Cove', N'STOKES', 1392),
		(N'Biltmore Forest', N'BUNCOMBE', 1400),
		(N'Cedar Point', N'CARTERET', 1415),
		(N'Pinebluff', N'MOORE', 1421),
		(N'Claremont', N'CATAWBA', 1432),
		(N'Robersonville', N'MARTIN', 1445),
		(N'Lake Waccamaw', N'COLUMBUS', 1484),
		(N'Pilot Mountain', N'SURRY', 1502),
		(N'Atlantic Beach', N'CARTERET', 1510),
		(N'East Spencer', N'ROWAN', 1514),
		(N'Glen Alpine', N'BURKE', 1535),
		(N'Manteo', N'DARE', 1540),
		(N'Holly Ridge', N'ONSLOW', 1541),
		(N'Bryson City', N'SWAIN', 1542),
		(N'Stanfield', N'STANLY/CABARRUS', 1548),
		(N'Hemby Bridge', N'UNION', 1551),
		(N'Jefferson', N'ASHE', 1560),
		(N'Snow Hill', N'GREENE', 1569),
		(N'Bethel', N'PITT', 1570),
		(N'Weldon', N'HALIFAX', 1570),
		(N'Denton', N'DAVIDSON', 1610),
		(N'Belhaven', N'BEAUFORT', 1625),
		(N'Murphy', N'CHEROKEE', 1631),
		(N'Dobson', N'SURRY', 1632),
		(N'Connelly Springs', N'BURKE', 1639),
		(N'Rose Hill', N'DUPLIN', 1682),
		(N'Ramseur', N'RANDOLPH', 1688),
		(N'Biscoe', N'MONTGOMERY', 1703),
		(N'Burnsville', N'YANCEY', 1703),
		(N'Navassa', N'BRUNSWICK', 1716),
		(N'Tryon', N'POLK', 1730),
		(N'Mount Pleasant', N'CABARRUS', 1756),
		(N'Bladenboro', N'BLADEN', 1765),
		(N'Sparta', N'ALLEGHANY', 1776),
		(N'Richlands', N'ONSLOW', 1780),
		(N'Andrews', N'CHEROKEE', 1785),
		(N'Pine Level', N'JOHNSTON', 1790),
		(N'Chadbourn', N'COLUMBUS', 1802),
		(N'Drexel', N'BURKE', 1842),
		(N'Calabash', N'BRUNSWICK', 1944),
		(N'Oakboro', N'STANLY', 1955),
		(N'Sharpsburg', N'NASH/EDGECOMBE/WILSON', 1960),
		(N'Scotland Neck', N'HALIFAX', 1964),
		(N'Badin', N'STANLY', 1965),
		(N'Hildebran', N'BURKE', 1978),
		(N'Four Oaks', N'JOHNSTON', 2008),
		(N'Yanceyville', N'CASWELL', 2018),
		(N'Franklinton', N'FRANKLIN', 2030),
		(N'Surf City', N'PENDER/ONSLOW', 2049),
		(N'Green Level', N'ALAMANCE', 2110),
		(N'Rockwell', N'ROWAN', 2124),
		(N'Taylorsville', N'ALEXANDER', 2124),
		(N'Hertford', N'PERQUIMANS', 2143),
		(N'Belville', N'BRUNSWICK', 2155),
		(N'Kure Beach', N'NEW HANOVER', 2162),
		(N'Cape Carteret', N'CARTERET', 2167),
		(N'Mars Hill', N'MADISON', 2167),
		(N'Princeville', N'EDGECOMBE', 2183),
		(N'Madison', N'ROCKINGHAM', 2210),
		(N'Spruce Pine', N'MITCHELL', 2224),
		(N'St. Pauls', N'ROBESON', 2228),
		(N'Laurel Park', N'HENDERSON', 2239),
		(N'Jonesville', N'YADKIN', 2251),
		(N'Coats', N'HARNETT', 2275),
		(N'Carthage', N'MOORE', 2307),
		(N'Haw River', N'ALAMANCE', 2358),
		(N'Maxton', N'ROBESON/SCOTLAND', 2374),
		(N'Norwood', N'STANLY', 2376),
		(N'Mayodan', N'ROCKINGHAM', 2438),
		(N'Enfield', N'HALIFAX', 2475),
		(N'Marshville', N'UNION', 2475),
		(N'Wilson''s Mills', N'JOHNSTON', 2503),
		(N'Tobaccoville', N'FORSYTH/STOKES', 2504),
		(N'Wrightsville Beach', N'NEW HANOVER', 2506),
		(N'Bermuda Run', N'DAVIE', 2577),
		(N'Troutman', N'IREDELL', 2624),
		(N'Fairmont', N'ROBESON', 2635),
		(N'Grifton', N'PITT/LENOIR', 2656),
		(N'Liberty', N'RANDOLPH', 2657),
		(N'Sylva', N'JACKSON', 2679),
		(N'Cajah''s Mountain', N'CALDWELL', 2751),
		(N'Wentworth', N'ROCKINGHAM', 2773),
		(N'La Grange', N'LENOIR', 2816),
		(N'Mineral Springs', N'UNION', 2905),
		(N'Southern Shores', N'DARE', 2916),
		(N'Yadkinville', N'YADKIN', 2923),
		(N'Swansboro', N'ONSLOW', 2940),
		(N'Nags Head', N'DARE', 2954),
		(N'Pembroke', N'ROBESON', 3030),
		(N'Granite Quarry', N'ROWAN', 3058),
		(N'River Bend', N'CRAVEN', 3063),
		(N'Rural Hall', N'FORSYTH', 3074),
		(N'Warsaw', N'DUPLIN', 3085),
		(N'Wallburg', N'DAVIDSON', 3102),
		(N'Landis', N'ROWAN', 3137),
		(N'Locust', N'STANLY/CABARRUS', 3204),
		(N'Murfreesboro', N'HERTFORD', 3225),
		(N'Whispering Pines', N'MOORE', 3262),
		(N'Flat Rock', N'HENDERSON', 3275),
		(N'Spencer', N'ROWAN', 3279),
		(N'Southport', N'BRUNSWICK', 3304),
		(N'Troy', N'MONTGOMERY', 3304),
		(N'Lillington', N'HARNETT', 3332),
		(N'Louisburg', N'FRANKLIN', 3351),
		(N'Maiden', N'CATAWBA/LINCOLN', 3393),
		(N'Red Springs', N'ROBESON/HOKE', 3396),
		(N'Benson', N'JOHNSTON', 3420),
		(N'Wilkesboro', N'WILKES', 3446),
		(N'Carolina Shores', N'BRUNSWICK', 3455),
		(N'Kitty Hawk', N'DARE', 3479),
		(N'Red Oak', N'NASH', 3487),
		(N'Polkton', N'ANSON', 3499),
		(N'Ranlo', N'GASTON', 3514),
		(N'Elizabethtown', N'BLADEN', 3576),
		(N'Fairview', N'UNION', 3603),
		(N'Wingate', N'UNION', 3608),
		(N'Lake Park', N'UNION', 3626),
		(N'Jamestown', N'GUILFORD', 3642),
		(N'Midland', N'CABARRUS/MECKLENBURG', 3648),
		(N'Stanley', N'GASTON', 3655),
		(N'Eastover', N'CUMBERLAND', 3662),
		(N'Lowell', N'GASTON', 3665),
		(N'Plymouth', N'WASHINGTON', 3700),
		(N'Emerald Isle', N'CARTERET', 3797),
		(N'Windsor', N'BERTIE', 3826),
		(N'Weaverville', N'BUNCOMBE', 3833),
		(N'Hudson', N'CALDWELL', 3890),
		(N'Wallace', N'DUPLIN/PENDER', 3984),
		(N'Sunset Beach', N'BRUNSWICK', 4010),
		(N'Gamewell', N'CALDWELL', 4016),
		(N'Elkin', N'SURRY/WILKES', 4022),
		(N'Trent Woods', N'CRAVEN', 4029),
		(N'Burgaw', N'PENDER', 4050),
		(N'Franklin', N'MACON', 4059),
		(N'Beaufort', N'CARTERET', 4171),
		(N'Rutherfordton', N'RUTHERFORD', 4173),
		(N'Randleman', N'RANDOLPH', 4177),
		(N'China Grove', N'ROWAN', 4224),
		(N'Tabor City', N'COLUMBUS', 4256),
		(N'Canton', N'HAYWOOD', 4275),
		(N'Shallotte', N'BRUNSWICK', 4304),
		(N'St. James', N'BRUNSWICK', 4316),
		(N'Spindale', N'RUTHERFORD', 4318),
		(N'Creedmoor', N'GRANVILLE', 4407),
		(N'Pittsboro', N'CHATHAM', 4415),
		(N'Valdese', N'BURKE', 4442),
		(N'North Wilkesboro', N'WILKES', 4477),
		(N'Erwin', N'HARNETT', 4566),
		(N'Mount Olive', N'WAYNE/DUPLIN', 4607),
		(N'Pleasant Garden', N'GUILFORD', 4616),
		(N'Granite Falls', N'CALDWELL', 4640),
		(N'Farmville', N'PITT', 4702),
		(N'Archer Lodge', N'JOHNSTON', 4708),
		(N'Zebulon', N'WAKE/JOHNSTON', 4709),
		(N'Dallas', N'GASTON', 4724),
		(N'Midway', N'DAVIDSON', 4762),
		(N'Boiling Springs', N'CLEVELAND', 4790),
		(N'Newport', N'CARTERET', 4817),
		(N'Cramerton', N'GASTON', 4822),
		(N'Ahoskie', N'HERTFORD', 4855),
		(N'Edenton', N'CHOWAN', 4857),
		(N'Raeford', N'HOKE', 4857),
		(N'Long View', N'CATAWBA/BURKE', 4867),
		(N'Angier', N'HARNETT/WAKE', 4934),
		(N'Ayden', N'PITT', 5007),
		(N'Walkertown', N'FORSYTH', 5032),
		(N'Sawmills', N'CALDWELL', 5155),
		(N'Nashville', N'NASH', 5303),
		(N'Mocksville', N'DAVIE', 5339),
		(N'Whiteville', N'COLUMBUS', 5352),
		(N'Rolesville', N'WAKE', 5362),
		(N'Bessemer City', N'GASTON', 5410),
		(N'Stokesdale', N'GUILFORD', 5535),
		(N'Wadesboro', N'ANSON', 5562),
		(N'Williamston', N'MARTIN', 5564),
		(N'Cherryville', N'GASTON', 5830),
		(N'Carolina Beach', N'NEW HANOVER', 5969),
		(N'Selma', N'JOHNSTON', 6227),
		(N'Boiling Spring Lakes', N'BRUNSWICK', 6297),
		(N'Wendell', N'WAKE', 6337),
		(N'Hamlet', N'RICHMOND', 6359),
		(N'Unionville', N'UNION', 6381),
		(N'Hillsborough', N'ORANGE', 6464),
		(N'Marvin', N'UNION', 6472),
		(N'Woodfin', N'BUNCOMBE', 6484),
		(N'Trinity', N'RANDOLPH', 6618),
		(N'Gibsonville', N'GUILFORD/ALAMANCE', 6938),
		(N'King', N'STOKES/FORSYTH', 6977),
		(N'Oak Ridge', N'GUILFORD', 7073),
		(N'Kill Devil Hills', N'DARE', 7127),
		(N'Mills River', N'HENDERSON', 7222),
		(N'Aberdeen', N'MOORE', 7360),
		(N'Oak Island', N'BRUNSWICK', 7366),
		(N'Forest City', N'RUTHERFORD', 7416),
		(N'Fletcher', N'HENDERSON', 7698),
		(N'Butner', N'GRANVILLE', 7788),
		(N'Brevard', N'TRANSYLVANIA', 7929),
		(N'Marion', N'MCDOWELL', 8117),
		(N'Roxboro', N'PERSON', 8185),
		(N'Conover', N'CATAWBA', 8301),
		(N'Wesley Chapel', N'UNION', 8380),
		(N'Black Mountain', N'BUNCOMBE', 8384),
		(N'Oxford', N'GRANVILLE', 8474),
		(N'Siler City', N'CHATHAM', 8552),
		(N'Clinton', N'SAMPSON', 8647),
		(N'Pineville', N'MECKLENBURG', 8725),
		(N'Rockingham', N'RICHMOND', 9293),
		(N'Morehead City', N'CARTERET', 9362),
		(N'Winterville', N'PITT', 9389),
		(N'Dunn', N'HARNETT', 9599),
		(N'Washington', N'BEAUFORT', 9639),
		(N'Waynesville', N'HAYWOOD', 9916),
		(N'Weddington', N'UNION/MECKLENBURG', 10324),
		(N'Elon', N'ALAMANCE', 10357),
		(N'Mount Airy', N'SURRY', 10361),
		(N'Lincolnton', N'LINCOLN', 10558),
		(N'Kings Mountain', N'CLEVELAND/GASTON', 10667),
		(N'Belmont', N'GASTON', 10954),
		(N'Tarboro', N'EDGECOMBE', 11066),
		(N'Smithfield', N'JOHNSTON', 11102),
		(N'Summerfield', N'GUILFORD', 11243),
		(N'Spring Lake', N'CUMBERLAND', 11777),
		(N'Archdale', N'RANDOLPH/GUILFORD', 11954),
		(N'Waxhaw', N'UNION', 12548),
		(N'Mebane', N'ALAMANCE/ORANGE', 12623),
		(N'Davidson', N'IREDELL/MECKLENBURG', 12692),
		(N'Newton', N'CATAWBA', 12982),
		(N'Lewisville', N'FORSYTH', 13046),
		(N'Southern Pines', N'MOORE', 13461),
		(N'Knightdale', N'WAKE', 13500),
		(N'Hendersonville', N'HENDERSON', 13824),
		(N'Reidsville', N'ROCKINGHAM', 14205),
		(N'Graham', N'ALAMANCE', 14304),
		(N'Mount Holly', N'GASTON', 14773),
		(N'Henderson', N'VANCE', 15094),
		(N'Roanoke Rapids', N'HALIFAX', 15186),
		(N'Eden', N'ROCKINGHAM', 15306),
		(N'Harrisburg', N'CABARRUS', 15387),
		(N'Stallings', N'UNION/MECKLENBURG', 15492),
		(N'Laurinburg', N'SCOTLAND', 15646),
		(N'Albemarle', N'STANLY', 15979),
		(N'Pinehurst', N'MOORE', 16123),
		(N'Hope Mills', N'CUMBERLAND', 16444),
		(N'Morganton', N'BURKE', 16716),
		(N'Leland', N'BRUNSWICK', 17154),
		(N'Elizabeth City', N'PASQUOTANK/CAMDEN', 17826),
		(N'Lenoir', N'CALDWELL', 17849),
		(N'Boone', N'WATAUGA', 18553),
		(N'Lexington', N'DAVIDSON', 18558),
		(N'Clayton', N'JOHNSTON/WAKE', 18734),
		(N'Clemmons', N'FORSYTH', 19575),
		(N'Shelby', N'CLEVELAND', 20089),
		(N'Havelock', N'CRAVEN', 20328),
		(N'Carrboro', N'ORANGE', 20558),
		(N'Kinston', N'LENOIR', 21025),
		(N'Lumberton', N'ROBESON', 21550),
		(N'Fuquay-Varina', N'WAKE', 22864),
		(N'Morrisville', N'WAKE/DURHAM', 23682),
		(N'Kernersville', N'FORSYTH/GUILFORD', 24211),
		(N'Statesville', N'IREDELL', 25363),
		(N'Asheboro', N'RANDOLPH', 25740),
		(N'Mint Hill', N'MECKLENBURG/UNION', 26170),
		(N'Thomasville', N'DAVIDSON/RANDOLPH', 27043),
		(N'Garner', N'WAKE', 28558),
		(N'Sanford', N'LEE', 28802),
		(N'Cornelius', N'MECKLENBURG', 29431),
		(N'New Bern', N'CRAVEN', 29823),
		(N'Holly Springs', N'WAKE', 30018),
		(N'Matthews', N'MECKLENBURG', 30359),
		(N'Salisbury', N'ROWAN', 34278),
		(N'Monroe', N'UNION', 34323),
		(N'Wake Forest', N'WAKE/FRANKLIN', 34463),
		(N'Goldsboro', N'WAYNE', 34945),
		(N'Indian Trail', N'UNION', 37449),
		(N'Mooresville', N'IREDELL', 37750),
		(N'Hickory', N'CATAWBA/BURKE/CALDWELL', 40351),
		(N'Apex', N'WAKE', 44745),
		(N'Kannapolis', N'ROWAN/CABARRUS', 45599),
		(N'Wilson', N'WILSON', 49357),
		(N'Burlington', N'ALAMANCE/GUILFORD', 52240),
		(N'Rocky Mount', N'NASH/EDGECOMBE', 55189),
		(N'Huntersville', N'MECKLENBURG', 55602),
		(N'Chapel Hill', N'ORANGE/DURHAM', 59569),
		(N'Gastonia', N'GASTON', 73843),
		(N'Jacksonville', N'ONSLOW', 77464),
		(N'Concord', N'CABARRUS', 87130),
		(N'Greenville', N'PITT', 87960),
		(N'Asheville', N'BUNCOMBE', 90918),
		(N'High Point', N'GUILFORD/DAVIDSON/RANDOLPH/FORSYTH', 109749),
		(N'Wilmington', N'NEW HANOVER', 115498),
		(N'Cary', N'WAKE/CHATHAM', 152627),
		(N'Fayetteville', N'CUMBERLAND', 208158),
		(N'Winston-Salem', N'FORSYTH', 238899),
		(N'Durham', N'DURHAM/ORANGE/WAKE', 250931),
		(N'Greensboro', N'GUILFORD', 282840),
		(N'Raleigh', N'WAKE/DURHAM', 440621),
		(N'Charlotte', N'MECKLENBURG', 818480);
END
GO
